/**
 * trig.c — Fixed-Point Trigonometry
 *
 * Q15 sin/cos: 256-entry quarter-wave lookup table + linear interpolation.
 *   Error < 1 LSB (< 3.1e-5 absolute) for all inputs.
 *
 * Q31 sin/cos: 32-iteration CORDIC (coordinate rotation digital computer).
 *   Uses only shifts and adds — no multiplication, no division, no FPU.
 *   Error < 2 LSBs (< 1e-9 absolute).
 *
 * Angle convention: angle_t (uint16_t)
 *   0x0000 = 0 rad, 0x4000 = π/2, 0x8000 = π, 0xC000 = 3π/2, wraps at 2π.
 */

#include "fixedpoint.h"

/* =========================================================================
 * Q15 Trig — Quarter-wave lookup table + linear interpolation
 * ========================================================================= */

/*
 * 257-entry table: SIN_TABLE[i] = round(sin(i * π/2 / 256) * 32767)
 * for i = 0..256.  The extra entry at [256] = 32767 lets us interpolate
 * all the way to the quadrant boundary without a branch.
 *
 * Generated by:
 *   python3 -c "
 *   import math
 *   t = [round(math.sin(i*math.pi/2/256)*32767) for i in range(257)]
 *   ..."
 */
static const int16_t SIN_TABLE[257] = {
         0,    201,    402,    603,    804,   1005,   1206,   1407,
      1608,   1809,   2009,   2210,   2410,   2611,   2811,   3012,
      3212,   3412,   3612,   3811,   4011,   4210,   4410,   4609,
      4808,   5007,   5205,   5404,   5602,   5800,   5998,   6195,
      6393,   6590,   6786,   6983,   7179,   7375,   7571,   7767,
      7962,   8157,   8351,   8545,   8739,   8933,   9126,   9319,
      9512,   9704,   9896,  10087,  10278,  10469,  10659,  10849,
     11039,  11228,  11417,  11605,  11793,  11980,  12167,  12353,
     12539,  12725,  12910,  13094,  13279,  13462,  13645,  13828,
     14010,  14191,  14372,  14553,  14732,  14912,  15090,  15269,
     15446,  15623,  15800,  15976,  16151,  16325,  16499,  16673,
     16846,  17018,  17189,  17360,  17530,  17700,  17869,  18037,
     18204,  18371,  18537,  18703,  18868,  19032,  19195,  19357,
     19519,  19680,  19841,  20000,  20159,  20317,  20475,  20631,
     20787,  20942,  21096,  21250,  21403,  21554,  21705,  21856,
     22005,  22154,  22301,  22448,  22594,  22739,  22884,  23027,
     23170,  23311,  23452,  23592,  23731,  23870,  24007,  24143,
     24279,  24413,  24547,  24680,  24811,  24942,  25072,  25201,
     25329,  25456,  25582,  25708,  25832,  25955,  26077,  26198,
     26319,  26438,  26556,  26674,  26790,  26905,  27019,  27133,
     27245,  27356,  27466,  27575,  27683,  27790,  27896,  28001,
     28105,  28208,  28310,  28411,  28510,  28609,  28706,  28803,
     28898,  28992,  29085,  29177,  29268,  29358,  29447,  29534,
     29621,  29706,  29791,  29874,  29956,  30037,  30117,  30195,
     30273,  30349,  30424,  30498,  30571,  30643,  30714,  30783,
     30852,  30919,  30985,  31050,  31113,  31176,  31237,  31297,
     31356,  31414,  31470,  31526,  31580,  31633,  31685,  31736,
     31785,  31833,  31880,  31926,  31971,  32014,  32057,  32098,
     32137,  32176,  32213,  32250,  32285,  32318,  32351,  32382,
     32412,  32441,  32469,  32495,  32521,  32545,  32567,  32589,
     32609,  32628,  32646,  32663,  32678,  32692,  32705,  32717,
     32728,  32737,  32745,  32752,  32757,  32761,  32765,  32766,
     32767,
};

/*
 * q15_sin_raw: sine for a phase angle in the first quadrant [0x0000, 0x4000].
 *
 * The top 8 bits of 'theta' index into SIN_TABLE (0..255).
 * The low 8 bits are the fractional position for linear interpolation.
 *
 * theta range: 0x0000..0x4000  →  sin range: 0..32767
 */
static q15_t q15_sin_raw(uint16_t theta)
{
    /* Scale: theta's [0, 0x4000] maps to table index [0, 256] */
    /* index = theta >> 6  gives 0..256 for theta 0..0x4000    */
    uint16_t idx   = theta >> 6;          /* 0..256  */
    uint16_t frac  = (theta & 0x3F) << 1; /* 0..126  (7-bit fraction) */

    int32_t  s0    = SIN_TABLE[idx];
    int32_t  s1    = SIN_TABLE[idx + 1]; /* safe: table has 257 entries */

    /* Linear interpolation: s0 + (s1-s0)*frac/128 */
    int32_t interp = s0 + (((s1 - s0) * (int32_t)frac) >> 7);
    return (q15_t)interp;
}

/*
 * q15_sin: full-range sine using quadrant symmetry.
 *
 * Quadrant map (angle_t):
 *   0x0000..0x3FFF  →  Q1: sin = +sin_raw(theta)
 *   0x4000..0x7FFF  →  Q2: sin = +sin_raw(0x8000 - theta)
 *   0x8000..0xBFFF  →  Q3: sin = -sin_raw(theta - 0x8000)
 *   0xC000..0xFFFF  →  Q4: sin = -sin_raw(0x10000 - theta)
 */
q15_t q15_sin(angle_t theta)
{
    int      sign = 1;
    uint16_t t    = theta;

    /* Fold into [0, 0x8000) using π symmetry */
    if (t >= 0x8000u) {
        t    -= 0x8000u;
        sign  = -1;
    }

    /* Fold into [0, 0x4000] using π/2 symmetry */
    uint16_t raw;
    if (t >= 0x4000u) {
        raw = (uint16_t)(0x8000u - t); /* reflect around π/2 */
    } else {
        raw = t;
    }

    q15_t s = q15_sin_raw(raw);
    return (sign > 0) ? s : q15_neg(s);
}

/* cos(theta) = sin(theta + π/2) */
q15_t q15_cos(angle_t theta)
{
    return q15_sin((angle_t)(theta + 0x4000u));
}


/* =========================================================================
 * Q31 Trig — CORDIC (32 iterations)
 * ========================================================================= */

/*
 * CORDIC theory:
 *   We rotate a unit vector iteratively. At step i, we rotate by
 *   ±arctan(2^-i). The angle table stores arctan(2^-i) scaled to
 *   the [0, 0x40000000] = [0, π/2] range.
 *
 *   After 32 iterations the vector magnitude is scaled by K ≈ 0.60725,
 *   so we pre-scale the starting vector by 1/K to compensate.
 *
 *   1/K ≈ 1.64676  →  in Q31: round(1.64676 * 2^31) = 0x26DD3B6A
 *   (We scale by half this: 0x136E9DB5 for the x component starting at 0.5)
 *
 *   Actually: start x = 1/K in Q31, y = 0, then result is (cos, sin).
 *
 * Angle table: ATAN_TABLE[i] = round(atan(2^-i) / (π/2) * 2^30)
 *   so 2^30 represents π/2 in phase units.
 */
static const int32_t ATAN_TABLE[32] = {
    0x20000000, /* atan(2^0)  = π/4       */
    0x12E4051E, /* atan(2^-1) = 26.565°   */
    0x09FB385B, /* atan(2^-2) = 14.036°   */
    0x051111D4, /* atan(2^-3)              */
    0x028B0D43,
    0x0145D7E1,
    0x00A2F61E,
    0x00517C55,
    0x0028BE53,
    0x00145F2F,
    0x000A2F98,
    0x000517CC,
    0x00028BE6,
    0x000145F3,
    0x0000A2FA,
    0x0000517D,
    0x000028BE,
    0x0000145F,
    0x00000A30,
    0x00000518,
    0x0000028C,
    0x00000146,
    0x000000A3,
    0x00000051,
    0x00000029,
    0x00000014,
    0x0000000A,
    0x00000005,
    0x00000003,
    0x00000001,
    0x00000001,
    0x00000000,
};

/*
 * 1/K in Q31: round(1/0.6072529350088814 * 2^31) = 0x26DD3B6A
 * This is the CORDIC gain compensation factor.
 */
#define CORDIC_K_INV_Q31  ((int32_t)0x4DBA76D4)

/*
 * q31_sincos: compute sin and cos simultaneously via CORDIC.
 *
 * theta: angle in [0, 0x40000000) = [0, π/2) (first quadrant).
 *        Represented as a fraction of π/2 in Q30 format.
 *
 * Outputs: *s_out = sin(theta) in Q31, *c_out = cos(theta) in Q31.
 */
static void q31_sincos_cordic(int32_t theta, q31_t *s_out, q31_t *c_out)
{
    int32_t x = CORDIC_K_INV_Q31; /* Start: (1/K, 0) vector, pre-scaled */
    int32_t y = 0;
    int32_t z = theta;             /* Remaining angle to rotate away     */

    for (int i = 0; i < 32; i++) {
        int32_t x_new, y_new;
        if (z >= 0) {
            /* Rotate counter-clockwise */
            x_new = x - (y >> i);
            y_new = y + (x >> i);
            z    -= ATAN_TABLE[i];
        } else {
            /* Rotate clockwise */
            x_new = x + (y >> i);
            y_new = y - (x >> i);
            z    += ATAN_TABLE[i];
        }
        x = x_new;
        y = y_new;
    }

    *c_out = (q31_t)x;
    *s_out = (q31_t)y;
}

/*
 * q31_sin: full-range Q31 sine using CORDIC + quadrant folding.
 *
 * The angle_t (0..0xFFFF = [0, 2π)) is mapped to the first quadrant
 * using the same symmetry as q15_sin, then CORDIC operates in [0, π/2).
 *
 * Internal CORDIC angle is in Q30 units where 0x40000000 = π/2.
 * angle_t first-quadrant value (0..0x4000) maps to Q30 by: << 16.
 */
q31_t q31_sin(angle_t theta)
{
    int      sign = 1;
    uint16_t t    = theta;

    if (t >= 0x8000u) { t -= 0x8000u; sign = -1; }

    uint16_t raw;
    if (t >= 0x4000u) {
        raw = (uint16_t)(0x8000u - t);
    } else {
        raw = t;
    }

    /* Scale raw (0..0x4000) to Q30 cordic angle (0..0x40000000) */
    int32_t cordic_angle = (int32_t)raw << 16;

    q31_t s, c;
    q31_sincos_cordic(cordic_angle, &s, &c);

    return (sign > 0) ? s : q31_neg(s);
}

q31_t q31_cos(angle_t theta)
{
    return q31_sin((angle_t)(theta + 0x4000u));
}
